version: '3'
services:
  gnpsquickstart-web:
    build:
      context: .
      dockerfile: Dockerfile.launchserver
    container_name: gnpsquickstart-web
    ports:
    - "5050:5000"
    volumes:
        - ./output:/output
    networks:
      - default
    restart: unless-stopped
    command: /app/run_server.sh
