version: '3'
services:
  web:
    build: .
    container_name: gnpsquickstart
    ports:
    - "5050:5000"
    volumes:
    - ../static:/app/static
    networks:
      - default
    restart: unless-stopped